### PR TITLE
chore: add wemeetagain as JavaScript member

### PR DESCRIPTION
**Pull request by wemeetagain**
### Summary
- add @wemeetagain as a member of the ipfs organization
- add @wemeetagain as a member of the Repos - JavaScript team

### Why do you need this?
I (@wemeetagain) am working with @achingbrain on maintaining and improving js-libp2p tooling and libraries, many of which exist in the ipfs organization. I would like to become a member of the javascript team so I can review PRs, take over stale PRs, etc. in these repos.

### What else do we need to know?
no deadline

**DRI:** @achingbrain @SgtPooki 

### Reviewer's Checklist

- [ ] It is clear where the request is coming from (if unsure, ask)
- [ ] All the automated checks passed
- [ ] The YAML changes reflect the summary of the request
- [ ] The Terraform plan posted as a comment reflects the summary of the request

### CODE REVIEW

**Review by laurentsenta — APPROVED** [review]
Good to see you again @wemeetagain  :)
Terraform plan looks good; waiting for @SgtPooki or @achingbrain to take a look and merge.

**Review by SgtPooki — APPROVED** [review]
LGTM

**Comment by SgtPooki** [comment]
@laurentsenta I don't have permissions to merge on github-mgmt

**Comment by galargh** [comment]
@wemeetagain FYI, you should receive an invite to your email inbox sometime soon. We do want to make it more obvious that this additional step is required for some operations, but we're not there yet.

**Comment by wemeetagain** [comment]
thanks @galargh

**Pull request merged**
