### PR TITLE
add self as collaborator to go-delegated-routing

### PR DESCRIPTION
**Pull request by willscott**
Have PRs, but can't tag reviewers.

Would make this as a PR I can tag reviewers against in this repo as requested by stewards, but can't per https://github.com/ipfs/github-mgmt/pull/30

### CODE REVIEW

**Comment by galargh** [comment]
I was wondering, can we add `go-delegated-routing` to `Repos - Go` instead? I can move forward with https://github.com/ipfs/github-mgmt/pull/32 if that's OK.

Also, do you happen to know why we have both `Repos - Go` and `Merge - Go` team? I suspect that it wasn't the case when they were being created but right now it seems that `Merge - Go` is a subset of `Repos - Go` so maybe we could consolidate the two.

**Comment by galargh** [comment]
> Have PRs, but can't tag reviewers.

Oh wait, that we can easily broaden. We could give everyone in the org triage access here which would allow requesting reviews - https://github.com/ipfs/github-mgmt/issues/33

**Comment by willscott** [comment]
Fine with #32 instead

**Comment by willscott** [comment]
Merge is a relatively small number of pretty trusted people. Those people should generally be okay to merge to e.g. protected main branches / cut releases. I would also assert that those people should have the trust to update repo permissions and add collaborators

**Comment by galargh** [comment]
Closing since I merged https://github.com/ipfs/github-mgmt/pull/32

> Merge is a relatively small number of pretty trusted people. Those people should generally be okay to merge to e.g. protected main branches / cut releases. I would also assert that those people should have the trust to update repo permissions and add collaborators

Got it. Just wondered because in practice `Merge - Go` has no more access to any repo than `Repos - Go`

**Pull request closed without merging**
