### PR TITLE
Update Mikeal access

### PR DESCRIPTION
**Pull request by andyschwab-admin**
### Summary
Remove access for Github account mikeal

### Why do you need this?
Reference RSS

**DRI:** andyschwab

### Reviewer's Checklist

- [ ] It is clear where the request is coming from (if unsure, ask)
- [ ] All the automated checks passed
- [ ] The YAML changes reflect the summary of the request
- [ ] The Terraform plan posted as a comment reflects the summary of the request

### CODE REVIEW

**Comment by galargh** [comment]
I see they were already removed through UI. Running sync now (it's going to make sure YML is in sync with GitHub) to see if there's anything left to clean up here.

**Comment by galargh** [comment]
https://github.com/ipfs/github-mgmt/actions/runs/5121428024

**Comment by andyschwab-admin** [comment]
> I see they were already removed through UI. Running sync now (it's going to make sure YML is in sync with GitHub) to see if there's anything left to clean up here.

Awesome, thanks!

**Comment by galargh** [comment]
No changes here 🥳

**Pull request closed without merging**
